package entitygen

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/nurularifin27/schemagen/dbtype"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

type Options struct {
	OutDir        string
	Driver        string
	Tables        []string
	ExcludeTables []string
	OnConflict    string
}

const generatedHeader = "// Code generated by schemagen.\n" +
	"// Manual code is allowed outside managed SECTION markers.\n"

var commonInitialisms = map[string]string{
	"api":   "API",
	"css":   "CSS",
	"dns":   "DNS",
	"html":  "HTML",
	"http":  "HTTP",
	"https": "HTTPS",
	"id":    "ID",
	"ip":    "IP",
	"json":  "JSON",
	"oauth": "OAuth",
	"otp":   "OTP",
	"sku":   "SKU",
	"sql":   "SQL",
	"ssh":   "SSH",
	"tls":   "TLS",
	"ttl":   "TTL",
	"ui":    "UI",
	"uid":   "UID",
	"uri":   "URI",
	"url":   "URL",
	"uuid":  "UUID",
	"xml":   "XML",
}

func Generate(db *gorm.DB, opts Options) error {
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output dir %s: %w", opts.OutDir, err)
	}

	tableList, err := resolveTables(db, opts.Tables, opts.ExcludeTables)
	if err != nil {
		return fmt.Errorf("failed to resolve tables: %w", err)
	}
	if len(tableList) == 0 {
		fmt.Println("no tables selected for generation")
		return nil
	}

	mapper := dbtype.New(opts.Driver)
	for _, table := range tableList {
		if err := syncEntityFile(db, mapper, table, opts); err != nil {
			return err
		}
	}

	return nil
}

func syncEntityFile(db *gorm.DB, mapper dbtype.Mapper, tableName string, opts Options) error {
	columnTypes, err := db.Migrator().ColumnTypes(tableName)
	if err != nil {
		return fmt.Errorf("failed to read column types for %s: %w", tableName, err)
	}

	structName := db.NamingStrategy.SchemaName(tableName)
	fields, imports := buildFields(columnTypes, mapper)
	fieldBlock := strings.Join(fields, "\n")
	importBlock := renderImportBlock(imports)

	fileName := schema.NamingStrategy{SingularTable: true}.TableName(structName) + ".go"
	filePath := filepath.Join(opts.OutDir, fileName)

	tableNameContent := fmt.Sprintf(
		"const TableName%s = %q\n\nfunc (*%s) TableName() string {\n\treturn TableName%s\n}",
		structName, tableName, structName, structName,
	)
	rendered := renderEntityFile(importBlock, tableNameContent, structName, fieldBlock)

	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		return writeFormatted(filePath, rendered)
	}

	raw, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	content := string(raw)
	if !isManagedFile(content) {
		return handleUnmanagedConflict(filePath, rendered, tableName, opts.OnConflict)
	}

	existingImports := extractExistingImports(content)
	mergedImports := mergeImports(filterManagedImports(existingImports), imports)
	newImportBlock := renderImportBlock(mergedImports)

	reImport := regexp.MustCompile(`(?s)import \((.*?)\)|import ".*?"`)
	if reImport.MatchString(content) {
		content = reImport.ReplaceAllString(content, newImportBlock)
	} else if newImportBlock != "" {
		content = strings.Replace(content, "package entity\n\n", "package entity\n\n"+newImportBlock+"\n\n", 1)
	}

	content = replaceSection(content,
		`// \[SECTION: TABLE_NAME: START\].*?// \[SECTION: TABLE_NAME: END\] - DO NOT REMOVE`,
		"// [SECTION: TABLE_NAME: START] - DO NOT REMOVE\n"+tableNameContent+"\n\n// [SECTION: TABLE_NAME: END] - DO NOT REMOVE",
	)

	content = replaceSection(content,
		`// \[SECTION: BASE: START\].*?// \[SECTION: BASE: END\] - DO NOT REMOVE`,
		"// [SECTION: BASE: START] - DO NOT REMOVE\n"+fieldBlock+"\n\t// [SECTION: BASE: END] - DO NOT REMOVE",
	)

	return writeFormatted(filePath, content)
}

func renderEntityFile(importBlock, tableNameContent, structName, fieldBlock string) string {
	return fmt.Sprintf(
		generatedHeader+
			"package entity\n\n%s\n\n"+
			"// [SECTION: TABLE_NAME: START] - DO NOT REMOVE\n"+
			"%s\n\n"+
			"// [SECTION: TABLE_NAME: END] - DO NOT REMOVE\n\n"+
			"type %s struct {\n"+
			"\t// [SECTION: BASE: START] - DO NOT REMOVE\n"+
			"%s\n"+
			"\t// [SECTION: BASE: END] - DO NOT REMOVE\n"+
			"}\n",
		importBlock, tableNameContent, structName, fieldBlock,
	)
}

func isManagedFile(content string) bool {
	return strings.Contains(content, "// [SECTION: TABLE_NAME: START] - DO NOT REMOVE") &&
		strings.Contains(content, "// [SECTION: BASE: START] - DO NOT REMOVE")
}

func handleUnmanagedConflict(filePath, rendered, tableName, onConflict string) error {
	switch onConflict {
	case "", "skip":
		log.Printf("skip unmanaged file for table %s: %s", tableName, filePath)
		return nil
	case "error":
		return fmt.Errorf("unmanaged file conflict for table %s: %s", tableName, filePath)
	case "backup":
		backupPath := fmt.Sprintf("%s.bak.%s", filePath, time.Now().Format("20060102150405"))
		if err := os.Rename(filePath, backupPath); err != nil {
			return fmt.Errorf("failed to backup unmanaged file %s: %w", filePath, err)
		}
		log.Printf("backed up unmanaged file for table %s: %s -> %s", tableName, filePath, backupPath)
		return writeFormatted(filePath, rendered)
	case "overwrite":
		log.Printf("overwrite unmanaged file for table %s: %s", tableName, filePath)
		return writeFormatted(filePath, rendered)
	default:
		return fmt.Errorf("unsupported on_conflict policy %q", onConflict)
	}
}

func buildFields(columnTypes []gorm.ColumnType, mapper dbtype.Mapper) ([]string, []string) {
	fields := make([]string, 0, len(columnTypes))
	importSet := make(map[string]bool)

	for _, col := range columnTypes {
		column := dbtype.FromGormColumn(col)
		fieldName := fieldNameFromColumn(column.Name)
		field := mapper.Map(column, fieldName)
		fields = append(fields, renderField(field, column.Name))
		for _, imp := range field.Imports {
			importSet[imp] = true
		}
	}

	imports := make([]string, 0, len(importSet))
	for imp := range importSet {
		imports = append(imports, imp)
	}
	sort.Strings(imports)
	return fields, imports
}

func fieldNameFromColumn(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})
	if len(parts) == 0 {
		return ""
	}

	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		lower := strings.ToLower(part)
		if initialism, ok := commonInitialisms[lower]; ok {
			b.WriteString(initialism)
			continue
		}
		b.WriteString(strings.ToUpper(lower[:1]))
		if len(lower) > 1 {
			b.WriteString(lower[1:])
		}
	}
	return b.String()
}

func renderField(field dbtype.Field, jsonName string) string {
	tags := append([]string{}, field.Tags...)
	return fmt.Sprintf("\t%s %s `gorm:%q json:%q`", field.Name, field.GoType, strings.Join(tags, ";"), jsonName)
}

func renderImportBlock(imports []string) string {
	if len(imports) == 0 {
		return ""
	}
	return "import (\n\t" + strings.Join(imports, "\n\t") + "\n)"
}

func replaceSection(src, pattern, replacement string) string {
	return regexp.MustCompile(`(?s)`+pattern).ReplaceAllString(src, replacement)
}

func writeFormatted(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return os.WriteFile(path, []byte(src), 0o644)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func resolveTables(db *gorm.DB, includes, excludes []string) ([]string, error) {
	if len(includes) > 0 {
		return includes, nil
	}

	all, err := db.Migrator().GetTables()
	if err != nil {
		return nil, err
	}

	skip := make(map[string]bool, len(excludes))
	for _, table := range excludes {
		skip[table] = true
	}

	var filtered []string
	for _, table := range all {
		if !skip[table] {
			filtered = append(filtered, table)
		}
	}
	return filtered, nil
}

func extractExistingImports(content string) []string {
	re := regexp.MustCompile(`(?s)import \((.*?)\)`)
	matches := re.FindStringSubmatch(content)
	if len(matches) < 2 {
		return nil
	}

	lines := strings.Split(matches[1], "\n")
	var imports []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" {
			imports = append(imports, line)
		}
	}
	return imports
}

func filterManagedImports(imports []string) []string {
	managed := map[string]bool{
		`"time"`:                           true,
		`"gorm.io/gorm"`:                   true,
		`"gorm.io/datatypes"`:              true,
		`"github.com/google/uuid"`:         true,
		`"github.com/shopspring/decimal"`:  true,
		`"github.com/jackc/pgx/v5/pgtype"`: true,
	}

	var filtered []string
	for _, imp := range imports {
		if !managed[imp] {
			filtered = append(filtered, imp)
		}
	}
	return filtered
}

func mergeImports(existing, generated []string) []string {
	seen := make(map[string]bool, len(existing)+len(generated))
	merged := make([]string, 0, len(existing)+len(generated))

	for _, imp := range existing {
		if !seen[imp] {
			seen[imp] = true
			merged = append(merged, imp)
		}
	}
	for _, imp := range generated {
		if !seen[imp] {
			seen[imp] = true
			merged = append(merged, imp)
		}
	}

	sort.Strings(merged)
	return merged
}
