package entitygen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/nurularifin27/schemagen/dbtype"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

type Options struct {
	OutDir           string
	Driver           string
	Renderer         string
	Tables           []string
	ExcludeTables    []string
	OnConflict       string
	DecimalStrategy  string
	JSONStrategy     string
	NullableStrategy string
	TypeOverrides    []dbtype.Override
	Relations        []Relation
	Logger           Logger
}

type GeneratedField struct {
	Name       string
	GoType     string
	ColumnName string
	GormTags   []string
	Imports    []string
}

type Relation struct {
	Table          string
	Kind           string
	Field          string
	TargetTable    string
	ForeignKey     string
	TargetKey      string
	JoinTable      string
	JoinForeignKey string
	JoinTargetKey  string
	SourceKey      string
}

type GeneratedRelation struct {
	Field   string
	GoType  string
	JSONTag string
	GORMTag string
}

type Logger struct {
	Infof    func(format string, args ...any)
	Verbosef func(format string, args ...any)
	Warnf    func(format string, args ...any)
}

type Result struct {
	Generated   int
	Skipped     int
	BackedUp    int
	Overwritten int
	Tables      int
}

const (
	RendererPlain = "plain"
	RendererSQLX  = "sqlx"
	RendererGORM  = "gorm"
)

const generatedHeader = "// Code generated by schemagen.\n" +
	"// Manual code is allowed outside managed SECTION markers.\n"

var commonInitialisms = map[string]string{
	"api":   "API",
	"css":   "CSS",
	"dns":   "DNS",
	"html":  "HTML",
	"http":  "HTTP",
	"https": "HTTPS",
	"id":    "ID",
	"ip":    "IP",
	"json":  "JSON",
	"oauth": "OAuth",
	"otp":   "OTP",
	"sku":   "SKU",
	"sql":   "SQL",
	"ssh":   "SSH",
	"tls":   "TLS",
	"ttl":   "TTL",
	"ui":    "UI",
	"uid":   "UID",
	"uri":   "URI",
	"url":   "URL",
	"uuid":  "UUID",
	"xml":   "XML",
}

type fileRenderer struct {
	name string
}

func newFileRenderer(name string) fileRenderer {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "", RendererSQLX:
		return fileRenderer{name: RendererSQLX}
	case RendererPlain:
		return fileRenderer{name: RendererPlain}
	case RendererGORM:
		return fileRenderer{name: RendererGORM}
	default:
		return fileRenderer{name: RendererSQLX}
	}
}

func Generate(db *gorm.DB, opts Options) (Result, error) {
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return Result{}, fmt.Errorf("failed to create output dir %s: %w", opts.OutDir, err)
	}

	tableList, err := resolveTables(db, opts.Tables, opts.ExcludeTables)
	if err != nil {
		return Result{}, fmt.Errorf("failed to resolve tables: %w", err)
	}
	if len(tableList) == 0 {
		if opts.Logger.Infof != nil {
			opts.Logger.Infof("no tables selected for generation")
		}
		return Result{}, nil
	}

	result := Result{Tables: len(tableList)}
	mapper := dbtype.New(opts.Driver, opts.DecimalStrategy, opts.JSONStrategy, opts.NullableStrategy, opts.TypeOverrides)
	renderer := newFileRenderer(opts.Renderer)
	for _, table := range tableList {
		if opts.Logger.Verbosef != nil {
			opts.Logger.Verbosef("processing table %s", table)
		}
		status, err := syncEntityFile(db, mapper, renderer, table, opts)
		if err != nil {
			return Result{}, err
		}
		switch status {
		case "generated":
			result.Generated++
		case "skipped":
			result.Skipped++
		case "backup":
			result.BackedUp++
			result.Generated++
		case "overwrite":
			result.Overwritten++
			result.Generated++
		}
	}

	return result, nil
}

func syncEntityFile(db *gorm.DB, mapper dbtype.Mapper, renderer fileRenderer, tableName string, opts Options) (string, error) {
	columnTypes, err := db.Migrator().ColumnTypes(tableName)
	if err != nil {
		return "", fmt.Errorf("failed to read column types for %s: %w", tableName, err)
	}

	structName := db.NamingStrategy.SchemaName(tableName)
	fields, imports := buildFields(tableName, columnTypes, mapper)
	fieldBlock := renderer.renderFieldBlock(fields)
	relations := buildRelations(tableName, opts.Relations)
	relationBlock := renderer.renderRelationBlock(relations)
	for _, rel := range relations {
		for _, imp := range rel.imports() {
			imports = append(imports, imp)
		}
	}
	imports = uniqueSortedImports(imports)
	importBlock := renderImportBlock(imports)

	fileName := schema.NamingStrategy{SingularTable: true}.TableName(structName) + ".go"
	filePath := filepath.Join(opts.OutDir, fileName)

	tableNameContent := renderer.renderTableSection(structName, tableName)
	rendered := renderEntityFile(importBlock, tableNameContent, structName, fieldBlock, relationBlock)

	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		if err := writeFormatted(filePath, rendered); err != nil {
			return "", err
		}
		if opts.Logger.Verbosef != nil {
			opts.Logger.Verbosef("generated %s", filePath)
		}
		return "generated", nil
	}

	raw, err := os.ReadFile(filePath)
	if err != nil {
		return "", err
	}
	content := string(raw)
	if !isManagedFile(content) {
		return handleUnmanagedConflict(filePath, rendered, tableName, opts.OnConflict, opts.Logger)
	}

	existingImports := extractExistingImports(content)
	mergedImports := mergeImports(filterManagedImports(existingImports), imports)
	newImportBlock := renderImportBlock(mergedImports)

	reImport := regexp.MustCompile(`(?s)import \((.*?)\)|import ".*?"`)
	if reImport.MatchString(content) {
		content = reImport.ReplaceAllString(content, newImportBlock)
	} else if newImportBlock != "" {
		content = strings.Replace(content, "package entity\n\n", "package entity\n\n"+newImportBlock+"\n\n", 1)
	}

	content = replaceSection(content,
		`// \[SECTION: TABLE_NAME: START\].*?// \[SECTION: TABLE_NAME: END\] - DO NOT REMOVE`,
		"// [SECTION: TABLE_NAME: START] - DO NOT REMOVE\n"+tableNameContent+"\n\n// [SECTION: TABLE_NAME: END] - DO NOT REMOVE",
	)

	content = replaceSection(content,
		`// \[SECTION: BASE: START\].*?// \[SECTION: BASE: END\] - DO NOT REMOVE`,
		"// [SECTION: BASE: START] - DO NOT REMOVE\n"+fieldBlock+"\n\t// [SECTION: BASE: END] - DO NOT REMOVE",
	)

	relationSection := "\t// [SECTION: RELATIONS: START] - DO NOT REMOVE\n"
	if relationBlock != "" {
		relationSection += relationBlock + "\n"
	}
	relationSection += "\t// [SECTION: RELATIONS: END] - DO NOT REMOVE"

	if strings.Contains(content, "// [SECTION: RELATIONS: START] - DO NOT REMOVE") {
		content = replaceSection(content,
			`// \[SECTION: RELATIONS: START\].*?// \[SECTION: RELATIONS: END\] - DO NOT REMOVE`,
			strings.TrimPrefix(relationSection, "\t"),
		)
	} else {
		content = strings.Replace(content,
			"\t// [SECTION: BASE: END] - DO NOT REMOVE",
			"\t// [SECTION: BASE: END] - DO NOT REMOVE\n\n"+relationSection,
			1,
		)
	}

	if err := writeFormatted(filePath, content); err != nil {
		return "", err
	}
	if opts.Logger.Verbosef != nil {
		opts.Logger.Verbosef("synced %s", filePath)
	}
	return "generated", nil
}

func renderEntityFile(importBlock, tableNameContent, structName, fieldBlock, relationBlock string) string {
	relationsSection := "\t// [SECTION: RELATIONS: START] - DO NOT REMOVE\n"
	if relationBlock != "" {
		relationsSection += relationBlock + "\n"
	}
	relationsSection += "\t// [SECTION: RELATIONS: END] - DO NOT REMOVE\n"

	return fmt.Sprintf(
		generatedHeader+
			"package entity\n\n%s\n\n"+
			"// [SECTION: TABLE_NAME: START] - DO NOT REMOVE\n"+
			"%s\n\n"+
			"// [SECTION: TABLE_NAME: END] - DO NOT REMOVE\n\n"+
			"type %s struct {\n"+
			"\t// [SECTION: BASE: START] - DO NOT REMOVE\n"+
			"%s\n"+
			"\t// [SECTION: BASE: END] - DO NOT REMOVE\n"+
			"\n%s"+
			"}\n",
		importBlock, tableNameContent, structName, fieldBlock, relationsSection,
	)
}

func isManagedFile(content string) bool {
	return strings.Contains(content, "// [SECTION: TABLE_NAME: START] - DO NOT REMOVE") &&
		strings.Contains(content, "// [SECTION: BASE: START] - DO NOT REMOVE")
}

func handleUnmanagedConflict(filePath, rendered, tableName, onConflict string, logger Logger) (string, error) {
	switch onConflict {
	case "", "skip":
		if logger.Warnf != nil {
			logger.Warnf("skip unmanaged file for table %s: %s", tableName, filePath)
		}
		return "skipped", nil
	case "error":
		return "", fmt.Errorf("unmanaged file conflict for table %s: %s", tableName, filePath)
	case "backup":
		backupPath := fmt.Sprintf("%s.bak.%s", filePath, time.Now().Format("20060102150405"))
		if err := os.Rename(filePath, backupPath); err != nil {
			return "", fmt.Errorf("failed to backup unmanaged file %s: %w", filePath, err)
		}
		if logger.Warnf != nil {
			logger.Warnf("backed up unmanaged file for table %s: %s -> %s", tableName, filePath, backupPath)
		}
		return "backup", writeFormatted(filePath, rendered)
	case "overwrite":
		if logger.Warnf != nil {
			logger.Warnf("overwrite unmanaged file for table %s: %s", tableName, filePath)
		}
		return "overwrite", writeFormatted(filePath, rendered)
	default:
		return "", fmt.Errorf("unsupported on_conflict policy %q", onConflict)
	}
}

func buildFields(tableName string, columnTypes []gorm.ColumnType, mapper dbtype.Mapper) ([]GeneratedField, []string) {
	fields := make([]GeneratedField, 0, len(columnTypes))
	importSet := make(map[string]bool)

	for _, col := range columnTypes {
		column := dbtype.FromGormColumn(col)
		column.TableName = tableName
		fieldName := fieldNameFromColumn(column.Name)
		field := mapper.Map(column, fieldName)
		fields = append(fields, GeneratedField{
			Name:       field.Name,
			GoType:     field.GoType,
			ColumnName: column.Name,
			GormTags:   append([]string{}, field.Tags...),
			Imports:    append([]string{}, field.Imports...),
		})
		for _, imp := range field.Imports {
			importSet[imp] = true
		}
	}

	imports := make([]string, 0, len(importSet))
	for imp := range importSet {
		imports = append(imports, imp)
	}
	return fields, uniqueSortedImports(imports)
}

func fieldNameFromColumn(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})
	if len(parts) == 0 {
		return ""
	}

	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		lower := strings.ToLower(part)
		if initialism, ok := commonInitialisms[lower]; ok {
			b.WriteString(initialism)
			continue
		}
		b.WriteString(strings.ToUpper(lower[:1]))
		if len(lower) > 1 {
			b.WriteString(lower[1:])
		}
	}
	return b.String()
}

func renderImportBlock(imports []string) string {
	if len(imports) == 0 {
		return ""
	}
	return "import (\n\t" + strings.Join(imports, "\n\t") + "\n)"
}

func replaceSection(src, pattern, replacement string) string {
	return regexp.MustCompile(`(?s)`+pattern).ReplaceAllString(src, replacement)
}

func writeFormatted(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return os.WriteFile(path, []byte(src), 0o644)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func resolveTables(db *gorm.DB, includes, excludes []string) ([]string, error) {
	if len(includes) > 0 {
		return includes, nil
	}

	all, err := db.Migrator().GetTables()
	if err != nil {
		return nil, err
	}

	skip := make(map[string]bool, len(excludes))
	for _, table := range excludes {
		skip[table] = true
	}

	var filtered []string
	for _, table := range all {
		if !skip[table] {
			filtered = append(filtered, table)
		}
	}
	return filtered, nil
}

func extractExistingImports(content string) []string {
	re := regexp.MustCompile(`(?s)import \((.*?)\)`)
	matches := re.FindStringSubmatch(content)
	if len(matches) < 2 {
		return nil
	}

	lines := strings.Split(matches[1], "\n")
	var imports []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" {
			imports = append(imports, line)
		}
	}
	return imports
}

func filterManagedImports(imports []string) []string {
	managed := map[string]bool{
		`"time"`:                           true,
		`"gorm.io/gorm"`:                   true,
		`"gorm.io/datatypes"`:              true,
		`"github.com/google/uuid"`:         true,
		`"github.com/shopspring/decimal"`:  true,
		`"github.com/jackc/pgx/v5/pgtype"`: true,
		`"encoding/json"`:                  true,
	}

	var filtered []string
	for _, imp := range imports {
		if !managed[imp] {
			filtered = append(filtered, imp)
		}
	}
	return filtered
}

func mergeImports(existing, generated []string) []string {
	seen := make(map[string]bool, len(existing)+len(generated))
	merged := make([]string, 0, len(existing)+len(generated))

	for _, imp := range existing {
		if !seen[imp] {
			seen[imp] = true
			merged = append(merged, imp)
		}
	}
	for _, imp := range generated {
		if !seen[imp] {
			seen[imp] = true
			merged = append(merged, imp)
		}
	}

	sort.Strings(merged)
	return merged
}

func uniqueSortedImports(imports []string) []string {
	seen := make(map[string]bool, len(imports))
	out := make([]string, 0, len(imports))
	for _, imp := range imports {
		if imp == "" || seen[imp] {
			continue
		}
		seen[imp] = true
		out = append(out, imp)
	}
	sort.Strings(out)
	return out
}

func (r fileRenderer) renderTableSection(structName, tableName string) string {
	if r.name == RendererGORM {
		return fmt.Sprintf(
			"const TableName%s = %q\n\nfunc (*%s) TableName() string {\n\treturn TableName%s\n}",
			structName, tableName, structName, structName,
		)
	}
	return fmt.Sprintf("const TableName%s = %q", structName, tableName)
}

func (r fileRenderer) renderFieldBlock(fields []GeneratedField) string {
	lines := make([]string, 0, len(fields))
	for _, field := range fields {
		lines = append(lines, r.renderField(field))
	}
	return strings.Join(lines, "\n")
}

func (r fileRenderer) renderRelationBlock(relations []GeneratedRelation) string {
	if len(relations) == 0 {
		return ""
	}
	lines := make([]string, 0, len(relations))
	for _, rel := range relations {
		lines = append(lines, r.renderRelation(rel))
	}
	return strings.Join(lines, "\n")
}

func (r fileRenderer) renderField(field GeneratedField) string {
	switch r.name {
	case RendererPlain:
		return fmt.Sprintf("\t%s %s", field.Name, field.GoType)
	case RendererGORM:
		return fmt.Sprintf(
			"\t%s %s `gorm:%q json:%q`",
			field.Name,
			field.GoType,
			strings.Join(append([]string{}, field.GormTags...), ";"),
			field.ColumnName,
		)
	default:
		return fmt.Sprintf(
			"\t%s %s `db:%q json:%q`",
			field.Name,
			field.GoType,
			field.ColumnName,
			field.ColumnName,
		)
	}
}

func (r fileRenderer) renderRelation(rel GeneratedRelation) string {
	switch r.name {
	case RendererGORM:
		return fmt.Sprintf("\t%s %s `gorm:%q json:%q`", rel.Field, rel.GoType, rel.GORMTag, rel.JSONTag)
	case RendererPlain:
		return fmt.Sprintf("\t%s %s `json:%q`", rel.Field, rel.GoType, rel.JSONTag)
	default:
		return fmt.Sprintf("\t%s %s `json:%q`", rel.Field, rel.GoType, rel.JSONTag)
	}
}

func buildRelations(tableName string, relations []Relation) []GeneratedRelation {
	if len(relations) == 0 {
		return nil
	}
	out := make([]GeneratedRelation, 0, len(relations))
	for _, rel := range relations {
		if rel.Table != tableName {
			continue
		}
		targetStruct := schema.NamingStrategy{}.SchemaName(rel.TargetTable)
		jsonTag := lowerCamel(rel.Field) + ",omitempty"
		switch rel.Kind {
		case "belongs_to", "has_one":
			out = append(out, GeneratedRelation{
				Field:   rel.Field,
				GoType:  "*" + targetStruct,
				JSONTag: jsonTag,
				GORMTag: fmt.Sprintf("foreignKey:%s;references:%s", fieldNameFromColumn(rel.ForeignKey), fieldNameFromColumn(rel.TargetKey)),
			})
		case "has_many":
			out = append(out, GeneratedRelation{
				Field:   rel.Field,
				GoType:  "[]*" + targetStruct,
				JSONTag: jsonTag,
				GORMTag: fmt.Sprintf("foreignKey:%s;references:%s", fieldNameFromColumn(rel.ForeignKey), fieldNameFromColumn(rel.TargetKey)),
			})
		case "many_to_many":
			out = append(out, GeneratedRelation{
				Field:   rel.Field,
				GoType:  "[]*" + targetStruct,
				JSONTag: jsonTag,
				GORMTag: fmt.Sprintf("many2many:%s;foreignKey:%s;joinForeignKey:%s;references:%s;joinReferences:%s", rel.JoinTable, fieldNameFromColumn(rel.SourceKey), fieldNameFromColumn(rel.JoinForeignKey), fieldNameFromColumn(rel.TargetKey), fieldNameFromColumn(rel.JoinTargetKey)),
			})
		}
	}
	return out
}

func (r GeneratedRelation) imports() []string {
	return nil
}

func lowerCamel(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}
