package entitygen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nurularifin27/schemagen/dbtype"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func TestIsManagedFile(t *testing.T) {
	managed := `// [SECTION: TABLE_NAME: START] - DO NOT REMOVE
// [SECTION: BASE: START] - DO NOT REMOVE`
	if !isManagedFile(managed) {
		t.Fatal("expected content to be treated as managed")
	}
	if isManagedFile("package entity\n") {
		t.Fatal("expected content without markers to be unmanaged")
	}
}

func TestHandleUnmanagedConflictSkip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "user.go")
	original := "package entity\n"
	if err := os.WriteFile(path, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := handleUnmanagedConflict(path, "package entity\n// new\n", "users", "skip"); err != nil {
		t.Fatalf("expected skip to succeed, got %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != original {
		t.Fatalf("expected original file to remain, got %q", string(got))
	}
}

func TestHandleUnmanagedConflictError(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "user.go")
	if err := os.WriteFile(path, []byte("package entity\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	err := handleUnmanagedConflict(path, "package entity\n// new\n", "users", "error")
	if err == nil || !strings.Contains(err.Error(), "unmanaged file conflict") {
		t.Fatalf("expected unmanaged conflict error, got %v", err)
	}
}

func TestHandleUnmanagedConflictBackup(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "user.go")
	original := "package entity\n// old\n"
	rendered := "package entity\n// new\n"
	if err := os.WriteFile(path, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := handleUnmanagedConflict(path, rendered, "users", "backup"); err != nil {
		t.Fatalf("expected backup to succeed, got %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "// new") {
		t.Fatalf("expected rendered content, got %q", string(got))
	}

	matches, err := filepath.Glob(path + ".bak.*")
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 1 {
		t.Fatalf("expected one backup file, got %d", len(matches))
	}
	backupContent, err := os.ReadFile(matches[0])
	if err != nil {
		t.Fatal(err)
	}
	if string(backupContent) != original {
		t.Fatalf("expected backup to keep original content, got %q", string(backupContent))
	}
}

func TestHandleUnmanagedConflictOverwrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "user.go")
	rendered := "package entity\n// new\n"
	if err := os.WriteFile(path, []byte("package entity\n// old\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := handleUnmanagedConflict(path, rendered, "users", "overwrite"); err != nil {
		t.Fatalf("expected overwrite to succeed, got %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "// new") {
		t.Fatalf("expected rendered content, got %q", string(got))
	}
}

func TestBuildFieldsUsesMapper(t *testing.T) {
	db, err := openSQLiteDB(t)
	if err != nil {
		t.Fatal(err)
	}
	if err := db.Exec(`CREATE TABLE users (id integer primary key autoincrement, name text not null, created_at datetime)`).Error; err != nil {
		t.Fatal(err)
	}
	columnTypes, err := db.Migrator().ColumnTypes("users")
	if err != nil {
		t.Fatal(err)
	}

	fields, imports := buildFields(columnTypes, dbtype.New("sqlite"))
	if len(fields) != 3 {
		t.Fatalf("expected 3 fields, got %d", len(fields))
	}
	if len(imports) == 0 {
		t.Fatal("expected generated imports for datetime field")
	}
}

func TestFieldNameFromColumnDoesNotSingularize(t *testing.T) {
	tests := map[string]string{
		"metadata":     "Metadata",
		"created_at":   "CreatedAt",
		"user_id":      "UserID",
		"product_sku":  "ProductSKU",
		"callback_url": "CallbackURL",
		"device_uuid":  "DeviceUUID",
		"raw_json":     "RawJSON",
	}

	for input, want := range tests {
		got := fieldNameFromColumn(input)
		if got != want {
			t.Fatalf("fieldNameFromColumn(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestGenerateCreatesManagedFile(t *testing.T) {
	db, err := openSQLiteDB(t)
	if err != nil {
		t.Fatal(err)
	}
	if err := db.Exec(`CREATE TABLE users (id integer primary key autoincrement, name text not null, created_at datetime)`).Error; err != nil {
		t.Fatal(err)
	}

	outDir := t.TempDir()
	err = Generate(db, Options{
		Driver:     "sqlite",
		OutDir:     outDir,
		Tables:     []string{"users"},
		OnConflict: "skip",
	})
	if err != nil {
		t.Fatalf("expected generate to succeed, got %v", err)
	}

	path := filepath.Join(outDir, "user.go")
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(content)
	required := []string{
		"Code generated by schemagen.",
		"Manual code is allowed outside managed SECTION markers.",
		"const TableNameUser = \"users\"",
		"type User struct {",
		"CreatedAt *time.Time",
	}
	for _, token := range required {
		if !strings.Contains(text, token) {
			t.Fatalf("expected generated file to contain %q, got:\n%s", token, text)
		}
	}
}

func TestGenerateUsesMetadataFieldName(t *testing.T) {
	db, err := openSQLiteDB(t)
	if err != nil {
		t.Fatal(err)
	}
	if err := db.Exec(`CREATE TABLE users (id integer primary key autoincrement, metadata text not null)`).Error; err != nil {
		t.Fatal(err)
	}

	outDir := t.TempDir()
	err = Generate(db, Options{
		Driver:     "sqlite",
		OutDir:     outDir,
		Tables:     []string{"users"},
		OnConflict: "skip",
	})
	if err != nil {
		t.Fatalf("expected generate to succeed, got %v", err)
	}

	content, err := os.ReadFile(filepath.Join(outDir, "user.go"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(content)
	if !strings.Contains(text, "Metadata string") {
		t.Fatalf("expected Metadata field, got:\n%s", text)
	}
	if strings.Contains(text, "Metadatum") {
		t.Fatalf("expected Metadatum to be absent, got:\n%s", text)
	}
}

func TestGeneratePreservesManualImportsOnManagedFile(t *testing.T) {
	db, err := openSQLiteDB(t)
	if err != nil {
		t.Fatal(err)
	}
	if err := db.Exec(`CREATE TABLE users (id integer primary key autoincrement, created_at datetime)`).Error; err != nil {
		t.Fatal(err)
	}

	outDir := t.TempDir()
	path := filepath.Join(outDir, "user.go")
	managed := `package entity

import (
	"strings"
)

// [SECTION: TABLE_NAME: START] - DO NOT REMOVE
const TableNameUser = "users"

func (*User) TableName() string {
	return TableNameUser
}

// [SECTION: TABLE_NAME: END] - DO NOT REMOVE

type User struct {
	// [SECTION: BASE: START] - DO NOT REMOVE
	ID int64 ` + "`gorm:\"column:id\" json:\"id\"`" + `
	// [SECTION: BASE: END] - DO NOT REMOVE
}

func (u User) Slug() string {
	return strings.ToLower("X")
}
`
	if err := os.WriteFile(path, []byte(managed), 0o644); err != nil {
		t.Fatal(err)
	}

	err = Generate(db, Options{
		Driver:     "sqlite",
		OutDir:     outDir,
		Tables:     []string{"users"},
		OnConflict: "skip",
	})
	if err != nil {
		t.Fatalf("expected generate to succeed, got %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(content)
	if strings.Count(text, "\"strings\"") != 1 {
		t.Fatalf("expected strings import exactly once, got:\n%s", text)
	}
	if strings.Count(text, "\"time\"") != 1 {
		t.Fatalf("expected time import exactly once, got:\n%s", text)
	}
	if !strings.Contains(text, "func (u User) Slug() string") {
		t.Fatalf("expected manual method to remain, got:\n%s", text)
	}
}

func openSQLiteDB(t *testing.T) (*gorm.DB, error) {
	t.Helper()
	path := filepath.Join(t.TempDir(), fmt.Sprintf("%s.db", strings.ReplaceAll(t.Name(), "/", "_")))
	return gorm.Open(sqlite.Open(path), &gorm.Config{})
}
